export enum ActionTypes {
  GET_USERS = 'GET_USERS',
  SET_USER_INFO = 'SET_USER_INFO',
  LOGIN_USER = 'LOGIN_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  REGISTER_USER = 'REGISTER_USER',
  SET_USER_ERROR = 'SET_USER_ERROR',
  SET_USER_SUCCESS = 'SET_USER_SUCCESS',
  SET_IS_USER_LOADING = 'SET_IS_USER_LOADING',
  SET_IS_USER_NOT_LOADING = 'SET_IS_USER_NOT_LOADING',
  SET_IS_USER_UPDATING = 'SET_IS_USER_UPDATING',
  SET_IS_USER_NOT_UPDATING = 'SET_IS_USER_NOT_UPDATING',
}

export const SET_USER_ERROR = 'SET_USER_ERROR';
