export enum ActionTypes {
  GET_USERS = "GET_USERS",
  SET_USER_ERROR = "SET_USER_ERROR",
  SET_USER_SUCCESS = "SET_USER_SUCCESS",
  SET_IS_USER_LOADING = "SET_IS_USER_LOADING",
  SET_IS_USER_NOT_LOADING = "SET_IS_USER_NOT_LOADING",
}
