export enum ActionTypes {
  ADD_CONCLUSION = "ADD_CONCLUSION",
  ADD_CONCLUSION_SUCCESS = "ADD_CONCLUSION_SUCCESS",
  ADD_CONCLUSION_ERROR = "ADD_CONCLUSION_ERROR",
  GET_ID_CONCLUSION = "GET_ID_CONCLUSION",
  GET_CONCLUSION = "GET_CONCLUSION",
  GET_CONCLUSION_SUCCESS = "GET_CONCLUSION_SUCCESS",
  GET_CONCLUSION_ERROR = "GET_CONCLUSION_ERROR",
}
