export const ADD_CONCLUSION = "ADD_CONCLUSION";
export const ADD_CONCLUSION_SUCCESS = "ADD_CONCLUSION_SUCCESS";
export const ADD_CONCLUSION_ERROR = "ADD_CONCLUSION_ERROR";

export const GET_ID = "GET_ID";

export const GET_CONCLUSION = "GET_CONCLUSION";
export const GET_CONCLUSION_SUCCESS = "GET_CONCLUSION_SUCCESS";
export const GET_CONCLUSION_ERROR = "GET_CONCLUSION_ERROR";
