export enum ActionTypes {
  GET_CANDIDATES = 'GET_CANDIDATES',
  GET_CANDIDATES_FILTERED = 'GET_CANDIDATES_FILTERED',
  GET_CANDIDATE_DETAIL = 'GET_CANDIDATE_DETAIL',
  SET_ERROR = 'SET_ERROR',
  CLEAN_ERROR = 'CLEAN_ERROR',
  CLEAN_FILTERS = 'CLEAN_FILTERS',
  CLEAN_SEARCH = 'CLEAN_SEARCH',
  SET_IS_LOADING = 'SET_IS_LOADING',
  SET_IS_NOT_LOADING = 'SET_IS_NOT_LOADING',
  SET_APPLIED_FILTERS = 'SET_APPLIED_FILTERS',
}

export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS';
export const ADD_CANDIDATE_ERROR = 'ADD_CANDIDATE_ERROR';

export const GET_ID = 'GET_ID';

export const GET_CANDIDATES = 'GET_CANDIDATES';

export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const GET_DATA_EDIT = 'GET_DATA_EDIT';
export const DATA_EDIT = 'DATA_EDIT';
export const DATA_EDIT_SUCCESS = 'DATA_EDIT_SUCCESS';
export const DATA_EDIT_ERROR = 'DATA_EDIT_ERROR';
