export enum ActionTypes {
  GET_CANDIDATES = 'GET_CANDIDATES',
  GET_CANDIDATES_FILTERED = 'GET_CANDIDATES_FILTERED',
  GET_CANDIDATE_DETAIL = 'GET_CANDIDATE_DETAIL',
  GENERATE_URL = 'GENERATE_URL',
  CLEAR_CANDIDATE_DETAIL = 'CLEAR_CANDIDATE_DETAIL',
  SET_CANDIDATE_ERROR = 'SET_CANDIDATE_ERROR',
  CLEAN_CANDIDATE_ERROR = 'CLEAN_CANDIDATE_ERROR',
  CLEAN_FILTERS = 'CLEAN_FILTERS',
  SET_IS_CANDIDATE_LOADING = 'SET_IS_CANDIDATE_LOADING',
  SET_IS_NOT_CANDIDATE_LOADING = 'SET_IS_NOT_CANDIDATE_LOADING',
  SET_CURRENT_FILTERS = 'SET_CURRENT_FILTERS',
  SET_DETAIL_FINISHED_LOADING = 'SET_DETAIL_FINISHED_LOADING',
  SET_CANDIDATE_SUCCESS = 'SET_CANDIDATE_SUCCESS',
  SET_IS_CANDIDATE_UPDATING = 'SET_IS_CANDIDATE_UPDATING',
  SET_TO_EDIT_INFO = 'SET_TO_EDIT_INFO',
  SET_IS_NOT_CANDIDATE_UPDATING = 'SET_IS_NOT_CANDIDATE_UPDATING',
  CLEAR_CANDIDATE_SUCCESS = 'CLEAR_CANDIDATE_SUCCESS',
  CREATE_CANDIDATE = 'CREATE_CANDIDATE',
  VALIDATE_TOKEN = 'VALIDATE_TOKEN',
  UPDATE_CONCLUSION = 'UPDATE_CONCLUSION',
  UPDATE_STATUS = 'UPDATE_STATUS',
  UPDATE_CANDIDATE_INFO = 'UPDATE_CANDIDATE_INFO',
}

export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS';
export const ADD_CANDIDATE_ERROR = 'ADD_CANDIDATE_ERROR';

export const GET_ID = 'GET_ID';

export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const GET_DATA_EDIT = 'GET_DATA_EDIT';
export const DATA_EDIT = 'DATA_EDIT';
export const DATA_EDIT_SUCCESS = 'DATA_EDIT_SUCCESS';
export const DATA_EDIT_ERROR = 'DATA_EDIT_ERROR';
