export enum ActionTypes {
  GET_ALL_POSITIONS = 'GET_ALL_POSITIONS',
  GET_POSITION_INFO = 'GET_POSITION_INFO',
  CREATE_POSITION = 'CREATE_POSITION',
  SET_IS_LOADING = 'SET_IS_LOADING',
  SET_IS_NOT_LOADING = 'SET_IS_NOT_LOADING',
  SET_ERROR = 'SET_ERROR',
  CLEAN_ERROR = 'CLEAN_ERROR',
}
